# Generated by Django 2.2.5 on 2019-09-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_No', models.IntegerField(null=True)),
                ('Invoice_Date', models.DateField()),
                ('Invoice_No', models.IntegerField(null=True)),
                ('Invoice_Amount', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_ID', models.IntegerField(null=True)),
                ('Equipment_Needed_from', models.DateField()),
                ('Equipment_Needed_Until', models.DateField()),
                ('PO_Num', models.IntegerField(null=True)),
                ('Receive_Date', models.DateField()),
                ('Buy_or_Rent', models.CharField(choices=[('buy', 'BUY'), ('rent', 'RENT')], default='rent', max_length=8)),
                ('Return_Date', models.DateField()),
                ('Receive_Hour', models.TimeField(null=True)),
                ('Return_Hour', models.TimeField(null=True)),
                ('Rental_Rate', models.CharField(max_length=50)),
                ('Enter_Equipment_ID', models.IntegerField(null=True)),
                ('Category', models.CharField(max_length=50)),
                ('Make', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Serial_Number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_ID', models.IntegerField(null=True)),
                ('Sales_Person', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
                ('Contact', models.CharField(max_length=10)),
            ],
        ),
    ]
